---
title: "bikeshare experiment 4"
output:
  pdf_document: default
  html_document:
    df_print: paged
---



```{r}
library(tidyverse)
library(here)
library(janitor)
library(rwunderground)
library(openmeteo)
```


```{r}
library(readr)
df1 <- read_csv("~/Documents/data sci/ds241_f23/Sarabia-Portfolio/data_raw/202309-capitalbikeshare-tripdata.csv.zip")

```
```{r}
df2s=df1 %>% 
  select(rideable_type,member_casual,
                    contains("start"),ride_id) %>% 
  mutate(start_stop="start") %>%
  rename(t=started_at,
         station_name=start_station_name,
         station_id=start_station_id,
         lat=start_lat,
         lng=start_lng)
df2e=df1 %>% 
  select(ride_id,rideable_type,member_casual,
                    contains("end")) %>%
  mutate(start_stop="stop") %>%
  rename(t=ended_at,
         station_name=end_station_name,
         station_id=end_station_id,
         lat=end_lat,
         lng=end_lng) 
df2=bind_rows(df2s,df2e) %>%
  arrange(t) %>%
  mutate(rider_delta=(start_stop=="start")*2-1) %>% #change in ridership 
  mutate(riders=cumsum(rider_delta)) %>%
  relocate(riders,.after=t)
```

```{r}
df2 %>% 
  ggplot(aes(t,riders)) +
  geom_line()
```
```{r}
df_s=df2 %>% slice_head(n=1000)
df_s %>% 
  ggplot(aes(t,riders)) +
  geom_line()
```

```{r}
df_e=df_s |>
  mutate(t_f=floor_date(t,"10 mins")) %>%
  relocate(t_f,.after=t) %>%
  slice_head(n=1,by=t_f)
```


```{r}
df_r=df2 |>
  mutate(t_f=floor_date(t,"10 mins")) %>%
  relocate(t_f,.after=t) %>%
  slice_head(n=1,by=t_f)

df_r %>% 
  ggplot(aes(t,riders)) +
  geom_line()
```
```{r}

p1=df2 %>% 

  filter(day(t)==18) %>%

  ggplot(aes(t,riders)) +

  geom_line() +

  ggtitle("Riders on 18Sep")
p1+

  geom_line(data=df_r %>% filter(day(t)==18),

  color="red")
```

```{r}
df_r=df2 |>
  mutate(t_f=floor_date(t,"1 mins")) %>%
  relocate(t_f,.after=t) %>%
  slice_head(n=1,by=t_f)

p1=df_r %>% 

  filter(day(t)==18) %>%
  ggplot(aes(t,riders)) +
  geom_line() + 
  ggtitle("Riders on 18Sep") 
p1+ 
  geom_line(data=df_r %>% filter(day(t)==18),
  color="red")
```

```{r}
df_w=weather_history("Washington",
                    start = "2023-09-01",
                    end = "2023-09-30",
                    hourly = c("apparent_temperature",
                               "wind_speed_10m",
                               "precipitation")
)
```
```{r}
df_s=df2 %>% slice_sample(n=1000)
df_j=df_s %>% left_join(df_w,
                        by=join_by(closest(t>=datetime)))
```


```{r}
df_j=df_s %>% 
  left_join(df_w,by=join_by(closest(t>=datetime)))  %>%
  relocate(datetime, .after=t) 
head(df_j)
```

```{r}
df_j$t[1:5]
df_j$datetime[1:5]
```

















