---
title: 'Experiment3: more airline data'
output:
  pdf_document: default
  html_document:
    df_print: paged
date: "2023-09-13"
---

```{r}
library(tidyverse)
library(janitor)
library(here)
```

```{r}
library(readr)
df2022 <- read_csv("~/Documents/data sci/ds241_f23/Sarabia-Portfolio/data_raw/DL_SelectFields 3.csv.zip")

df2022=df2022 %>% clean_names()
```

```{r}
df9=df2022 |>
  filter(passengers>0,origin=="LGA")
```

```{r}
df9 |> ggplot(aes(month)) + geom_bar()
```

```{r}
df9 |> ggplot(aes(month)) + geom_bar(aes(weight=departures_performed))
```

```{r}
df9 |> ggplot(aes(month)) + geom_bar(aes(weight=passengers))
```

```{r}
df9 |> ggplot(aes(month,fill=carrier_name)) + geom_bar(aes(weight=departures_performed)) 
```

```{r}
df10=df2022 |> filter(passengers>0,origin=="LGA" | dest=="LGA")
df10 |> ggplot(aes(month)) +geom_bar(aes(weight=passengers))
```

```{r}
df11=df10 |> select(month,passengers,seats,carrier_name, dest, origin)
```

```{r}
df12=df10 |> select(1:5, month, contains("id"))
```

```{r}
df13=df11 |> mutate(percent_loading = passengers/seats*100)

df13 |> ggplot(aes(percent_loading))+
  geom_histogram()+facet_wrap(~carrier_name,scales="free_y")
```











